sudo: false
language: python
os:
  - linux
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
env:
  - PYTEST="pytest" VIRTUALENV="virtualenv" FLAKE8="flake8"
matrix:
  include:
    - python: 2.7
      env: PY="24" FLAKE8="" PYTEST="py==1.4.12 pytest==2.3.3" VIRTUALENV="virtualenv==1.7.2"
    - python: 2.7
      env: PY="25" FLAKE8="" PYTEST="py==1.4.19 pytest==2.5.0" VIRTUALENV="virtualenv==1.9.1" PIP_OPT="--insecure"
    - python: 2.7
      env: PY="pypy3" FLAKE8=""
install:
  - mkdir builds
  - pushd builds
  - case "${PY-}" in
      24)
        /bin/sh ../.travis-make-py24-virtualenv.sh $PWD/ve
        ;;
      25)
        /bin/sh ../.travis-make-py25-virtualenv.sh $PWD/ve
        ;;
      pypy3)
        /bin/sh ../.travis-pypy3-virtualenv.sh $PWD/ve;
        ;;
      esac
  - if [ -d "$PWD/ve" ]; then source $PWD/ve/bin/activate; fi
  - pip install ${PIP_OPT} ${FLAKE8} ${PYTEST} ${VIRTUALENV}
  - popd
script:
  - python -V
  - if [ -n "${FLAKE8}" -a $TRAVIS_PYTHON_VERSION != '2.6' ]; then echo "running flake"; flake8 --ignore=E501 --builtins=basestring --exclude=tests/guinea-pigs; fi
  - python setup.py test
