sudo: required
language: python
os:
  - linux
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3.5"
before_install:
  - sudo apt-get install -y python-dev libpython-dev pypy-dev
install:
  - sudo pip install --upgrade setuptools pip
  - pip install flake8 virtualenv pytest
script:
  - python -V
  - if [ $TRAVIS_PYTHON_VERSION != '2.6' ]; then echo "running flake"; flake8 --ignore=E501 --exclude=tests/guinea-pigs; fi
  - python setup.py test
