language: python
os:
  - linux
  - osx
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - pip install flake8
script:
  - flake8 --ignore=E501 --builtins=basestring --exclude=tests/guinea-pigs
  - python setup.py test
