sudo: false
language: python
os:
  - linux
dist: xenial
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3.5"
install:
  - pip install flake8 virtualenv pytest
script:
  - python -V
  - if [ $TRAVIS_PYTHON_VERSION != '2.6' ]; then echo "running flake"; flake8 --ignore=E501 --exclude=tests/guinea-pigs; fi
  - python setup.py test
