version: '{build}'
environment:
  matrix:
  - PYTHON_HOME: C:\Python27
  - PYTHON_HOME: C:\Python34
  - PYTHON_HOME: C:\Python35
  - PYTHON_HOME: C:\Python36
  - PYTHON_HOME: C:\Python36-x64
install:
- appveyor DownloadFile https://bootstrap.pypa.io/get-pip.py
- '%PYTHON_HOME%\python get-pip.py'
build_script:
- '%PYTHON_HOME%\python setup.py sdist'
test_script:
- '%PYTHON_HOME%\python setup.py test'
